cache:
  paths:
    - node_modules/

before_script:
  - whoami
  - hostname

stages:
  - build
  - sync

build_win:
  stage: build
  image: electronuserland/builder:wine
  only:
    - main
  artifacts:
    paths:
      - release
    expire_in: 30 mins
  script: npm i && npm run build:win

build_linux:
  stage: build
  only:
    - main
  tags:
    - tencent
  artifacts:
    paths:
      - release
    expire_in: 30 mins
  script: cnpm i && npm run build:linux

sync:
  stage: sync
  only:
    - main
  tags:
    - tencent
  script: |
    # 将markdown数据库、构建好的APP同步到网页版
    if [ -d /www/wwwroot/wiki.kuaiyc.com/production/markdown ]; then
      rm -rf /www/wwwroot/wiki.kuaiyc.com/production/markdown
    fi
    pwd
    ls -alh
    cp -r markdown /www/wwwroot/wiki.kuaiyc.com/production/markdown
    cp -r release /www/wwwroot/wiki.kuaiyc.com/production/public/release
    cd /www/wwwroot/wiki.kuaiyc.com/production
    npm run mix
    php artisan lesson:sync
    php artisan page-cache:clear