cache:
  paths:
    - node_modules/

before_script:
  - whoami
  - hostname
  # - cat /proc/cpuinfo
  # - cat /proc/meminfo

stages:
  - build
  - sync

# build_win:
#   stage: build
#   image: electronuserland/builder:wine
#   only:
#     - main
#   artifacts:
#     paths:
#       - release
#     expire_in: 30 mins
#   script: |
#     npm install node-gyp@latest -g
#     npm i
#     npm run rebuild 
#     npm run build:win

# build_linux:
#   stage: build
#   image: electronuserland/builder:latest
#   only:
#     - main
#   artifacts:
#     paths:
#       - release
#     expire_in: 30 mins
#   script:
#     - npm config set registry https://registry.npm.taobao.org/
#     - npm install -g npm@8.15.0
#     - npm install node-gyp@latest -g
#     - npm -v
#     - npm ci
#     - npm run rebuild 
#     - npm run build

sync:
  stage: sync
  only:
    - main
  tags:
    - tencent
  script: rm -rf /www/database/lessons.db && cp -rf database/database.db /www/database/lessons.db