cache:
  paths:
    - node_modules/

before_script:
  - whoami
  - hostname

stages:
  - run
  - connect

run:
  stage: run
  only:
    - main
  tags:
    - tencent
  artifacts:
    paths:
      - release
    expire_in: 20 mins
  script: |
    pwd
    cnpm i
    npm run build

# 将markdown数据库、构建好的APP同步到网页版
connect:
  stage: connect
  only:
    - main
  tags:
    - tencent
  script: |
    if [ -d /www/wwwroot/wiki.kuaiyc.com/production/markdown ]; then
      rm -rf /www/wwwroot/wiki.kuaiyc.com/production/markdown
    fi
    pwd
    ls -alh
    cp -r markdown /www/wwwroot/wiki.kuaiyc.com/production/markdown
    cp -r release /www/wwwroot/wiki.kuaiyc.com/production/public/release
    cd /www/wwwroot/wiki.kuaiyc.com/production
    npm run mix
    php artisan lesson:sync
    php artisan page-cache:clear