cache:
  paths:
    - node_modules/

before_script:
  - whoami
  - hostname

stages:
  - build
  - sync

# build_win:
#   stage: build
#   image: electronuserland/builder:wine
#   only:
#     - main
#   artifacts:
#     paths:
#       - release
#     expire_in: 30 mins
#   script: npm i && npm run build:win

# build_linux:
#   stage: build
#   only:
#     - main
#   tags:
#     - tencent
#   artifacts:
#     paths:
#       - release
#     expire_in: 30 mins
#   script: cnpm i && npm run build:linux

sync:
  stage: sync
  only:
    - main
  tags:
    - tencent
  script: |
    # 将markdown数据库同步到网页版
    rm -rf /www/database/lessons.db
    cp -rf database/database.db /www/database