on:
  push:
    tags:
      - 'v*' 

permissions:
  contents: write

name: Upload Release Asset

jobs:
  build:
    runs-on: ${{ matrix.os }}   
    strategy:      
      matrix:        
        os: [ubuntu-latest,macos-latest,windows-latest]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm ci

      - name: Install node-gyp
        run: npm install node-gyp@latest -g

      - name: Rebuild
        run: npm run rebuild

      - name: Build Release Files
        run: npm run build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: 检查文件(macOS、Ubuntu)
        if: matrix.os != 'windows-latest'
        run: |
          ls -alh release

      - name: 检查文件(Windows)
        if: matrix.os == 'windows-latest'
        run: |
          dir release

      - name: 上传构件
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.os }}
          path: |
            release/*.exe 
            release/*.dmg
            release/*.AppImage
            release/*.snap
          retention-days: 5

  release:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: 下载构件
        uses: actions/download-artifact@v3
      - name: 检查文件
        run: ls -alhR
      - name: 发布版本
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            *.dmg
            *.exe
            *.AppImage
            *.snap

  sync:
    runs-on: self-hosted
    needs: build
    steps:
      - name: 下载构件
        uses: actions/download-artifact@v3
        with:
          path: .
      - name: 检查文件
        run: ls -alhR
      - name: 扁平化
        run: |
          mkdir flattened
          find . -type f -exec cp {} flattened/
      - name: 检查文件
        run: ls -alhR
      - name: 同步到服务器
        run: |
          if [ ! -d "/www/storage/kuaiyizhi_desktop_temp/" ]; then
            mkdir "/www/storage/kuaiyizhi_desktop_temp/"
          fi

          cp flattened/* /www/storage/kuaiyizhi_desktop_temp/
          rm -rf /www/storage/kuaiyizhi_desktop
          mv /www/storage/kuaiyizhi_desktop_temp /www/storage/kuaiyizhi_desktop
            