name: Build

on:
  push:
    branches:
      - main
    paths-ignore:
      - "**.md"
      - "**.spec.js"
      - ".idea"
      - ".vscode"
      - ".dockerignore"
      - "Dockerfile"
      - ".gitignore"
      - ".github/**"
      - "!.github/workflows/build.yml"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: make file 
        run: touch release/x.txt

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          path: release/
          retention-days: 5

      - name: Create release
        run: |
          git tag v${{ env.npm_package_version }}
          git push --tags

      - name: Upload release assets
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ env.RELEASE_URL }}
          asset_path: ./release
          asset_name: MyElectronApp-${{ env.npm_package_version }}.zip
          asset_content_type: application/zip
