on:
  push:
    branches:
      - main

permissions:
  contents: write

name: Build and Release

jobs:
  update_version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: '检查 package.json'
        run: cat ./package.json

      - name: 'Automated Version Bump'
        id: version-bump
        uses: 'phips28/gh-action-bump-version@master'
        with:
          tag-prefix: 'v'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      - name: '检查 package.json'
        run: cat ./package.json
        
      - name: 输出新的版本号
        env:
          NEW_TAG: ${{ steps.version-bump.outputs.newTag }}
        run: |
          echo "新版本号 $NEW_TAG"
          echo $NEW_TAG >> tag

      - name: 上传版本号构件
        uses: actions/upload-artifact@v3
        with:
          name: tag
          path: tag
          retention-days: 1

  test:
    runs-on: ubuntu-latest
    needs: 
      - update_version
    steps:
      - name: 下载版本号构件
        uses: actions/download-artifact@v3
        with: 
          name: tag

      - name: 存储版本号到环境变量
        run: |
          echo "tag=$(cat tag)" >> $GITHUB_ENV 

      - name: 检查tag-1
        run: echo ${{ env.tag }}
        
      - name: 检查tag-2
        env: 
          TAG: ${{ env.tag }}
        run: echo $TAG

      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          ref: ${{ env.tag }}

      - name: '检查 package.json'
        run: cat ./package.json

  build:
    runs-on: ${{ matrix.os }}   
    needs: update_version
    strategy:      
      matrix:        
        os: [ubuntu-latest,macos-latest,windows-latest]

    steps:
      - name: 下载版本号构件
        uses: actions/download-artifact@v3
        with: 
          name: tag

      - name: 存储版本号到环境变量(Windows)
        if: matrix.os == 'windows-latest'
        run: echo tag=$(Get-Content tag) >> $env:GITHUB_ENV

      - name: 存储版本号到环境变量(macOS、Ubuntu)
        if: matrix.os != 'windows-latest'
        run: echo "tag=$(cat tag)" >> $GITHUB_ENV

      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          ref: ${{ env.tag }}

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm ci

      - name: Install node-gyp
        run: npm install node-gyp@latest -g

      - name: Rebuild
        run: npm run rebuild

      - name: Build Release Files
        run: npm run build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: 检查文件(macOS、Ubuntu)
        if: matrix.os != 'windows-latest'
        run: ls -alh release
      
      - name: 检查文件(Windows)
        if: matrix.os == 'windows-latest'
        run: |
          dir release

      - name: 上传构件
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.os }}
          path: |
            release/*.exe 
            release/*.dmg
            release/*.AppImage
            release/*.snap
          retention-days: 5

  # 把css文件单独构建出来，可供其他平台展示文档时使用
  build_css:
    runs-on: ubuntu-latest
    needs: update_version

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: 安装依赖
        run: npm ci

      - name: 构建CSS文件
        run: npx tailwindcss -i ./src/app.css -o kuaiyizhi.css -m

      - name: 检查文件
        run: ls -alh 

      - name: 上传构件
        uses: actions/upload-artifact@v3
        with:
          name: kuaiyizhi.css
          path: kuaiyizhi.css
          retention-days: 5

  release:
    runs-on: ubuntu-latest
    needs: 
      - build
      - update_version
    steps:
      - name: 下载 tag
        uses: actions/download-artifact@v3
        with: 
          name: tag

      - name: 下载 macos-latest
        uses: actions/download-artifact@v3
        with: 
          name: macos-latest

      - name: 下载 ubuntu-latest
        uses: actions/download-artifact@v3
        with: 
          name: ubuntu-latest
          
      - name: 下载 windows-latest
        uses: actions/download-artifact@v3
        with: 
          name: windows-latest

      - name: 检查文件
        run: ls -alhR

      - name: 存储版本号到环境变量
        run: echo "tag=$(cat tag)" >> $GITHUB_ENV 

      - name: 发布版本
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ env.tag }}
          files: |
            ./**/*.dmg
            ./**/*.exe
            ./**/*.AppImage
            ./**/*.snap

  sync:
    runs-on: self-hosted
    needs: build
    steps:
      - name: 准备文件夹
        run: |
          rm -rf downloads && mkdir downloads
          rm -rf /www/storage/kuaiyizhi_desktop_temp/
          mkdir /www/storage/kuaiyizhi_desktop_temp/

      - name: 下载 macos-latest
        uses: actions/download-artifact@v3
        with: 
          name: macos-latest

      - name: 下载 ubuntu-latest
        uses: actions/download-artifact@v3
        with: 
          name: ubuntu-latest
          
      - name: 下载 windows-latest
        uses: actions/download-artifact@v3
        with: 
          name: windows-latest

      - name: 检查文件
        run: ls -alhR

      - name: 扁平化
        run: |
          find . -type f -exec cp {} /www/storage/kuaiyizhi_desktop_temp/ \;

      - name: 检查文件
        run: ls -alhR /www/storage/kuaiyizhi_desktop_temp

      - name: 同步到服务器
        run: |
          rm -rf /www/storage/kuaiyizhi_desktop
          mv /www/storage/kuaiyizhi_desktop_temp /www/storage/kuaiyizhi_desktop
          cp -rf database/database.db /www/database/lessons.db

      - name: 下载 CSS 构件
        uses: actions/download-artifact@v3
        with:
          name: kuaiyizhi.css

      - name: 检查文件
        run: ls -alhR

      - name: 同步到服务器
        run: |
          cp -f kuaiyizhi.css /www/wwwroot/www.kuaiyizhi.cn/production/public/