on:
  push:
    tags:
      - 'v*' 

permissions:
  contents: write

name: Upload Release Asset

jobs:
  build:
    runs-on: ${{ matrix.os }}   
    strategy:      
      matrix:        
        os: [macos-latest,ubuntu-latest,windows-latest]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm ci

      - name: Install node-gyp
        run: npm install node-gyp@latest -g

      - name: Rebuild
        run: npm run rebuild

      - name: Build Release Files
        run: npm run build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: 检查文件
        if: matrix.os != 'windows-latest'
        run: |
          ls -alh release

      - name: 检查文件
        if: matrix.os == 'windows-latest'
        run: |
          dir release

      - name: 压缩文件
        run: zip -r release.zip release 

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.os }}
          path: release.zip
          retention-days: 5

  release:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: 下载构件
        uses: actions/download-artifact@v3
        with:
          path: release
      - name: 检查文件
        run: |
          ls -alh release
      - name: 解压文件
        run: |
          find release -type f -name "*.zip" -exec unzip {} \;
      - name: 发布版本
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            release/macos-latest/*
            release/ubuntu-latest/*
            release/windows-latest/*
          exclude: |
            file3.txt
            folder1/
            *.yaml
            *.blockmap

  sync:
    runs-on: self-hosted
    needs: build
    steps:
      - name: 下载构件
        uses: actions/download-artifact@v3
        with:
          path: release
      - name: 检查文件
        run: |
          ls -alh release
      - name: 解压文件
        run: |
          find release -type f -name "*.zip" -exec unzip {} \;
      - name: 同步到服务器
        run: |
          cp -rf release /www/storage/kuaiyizhi_desktop
            